version: "3.8"
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: study
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
  ns:
    build:
      context: .
    environment:
      - NODE_ENV=development
      - DB_NAME=study
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1234
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./src/:/src/
    depends_on:
      - db